export const members = [
  {
    id: 1,
    name: 'John Doe',
    role: 'Volunteer',
    avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    skills: ['Event Planning', 'Fundraising', 'Public Speaking'],
    aiMatch: 95,
  },
  {
    id: 2,
    name: 'Jane Smith',
    role: 'Coordinator',
    avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    skills: ['Graphic Design', 'Social Media', 'Content Writing'],
    aiMatch: 92,
  },
  {
    id: 3,
    name: 'Samuel Green',
    role: 'Member',
    avatarUrl: 'https://randomuser.me/api/portraits/men/33.jpg',
    skills: ['Web Development', 'Database Management'],
    aiMatch: 88,
  },
  {
    id: 4,
    name: 'Emily White',
    role: 'Volunteer',
    avatarUrl: 'https://randomuser.me/api/portraits/women/34.jpg',
    skills: ['First Aid', 'Logistics'],
    aiMatch: 85,
  },
    {
    id: 5,
    name: 'Chris Brown',
    role: 'Member',
    avatarUrl: 'https://randomuser.me/api/portraits/men/35.jpg',
    skills: ['Music', 'Sound Engineering'],
    aiMatch: 82,
  },
  {
    id: 6,
    name: 'Sarah Wilson',
    role: 'Coordinator',
    avatarUrl: 'https://randomuser.me/api/portraits/women/36.jpg',
    skills: ['Project Management', 'Team Leadership'],
    aiMatch: 98,
  },
];
